export const CONNECTED = 'CONNECTED';
export const DISCONNECTED = 'DISCONNECTED';
export const INCOMING_MESSAGE = 'INCOMING_MESSAGE';
export const INCOMING_MESSAGE_SEEN = 'INCOMING_MESSAGE_SEEN';

export const IDENTIFY_USER = 'IDENTIFY_USER';
export const IDENTIFYING_USER_SUCCEEDED = 'IDENTIFYING_USER_SUCCEEDED';
export const IDENTIFYING_USER_FAILED = 'IDENTIFYING_USER_FAILED';